papra-hq/papra

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
> chore(github): added contribution guidelines

- .github/workflows/ci-apps-papra-client.yaml
- CONTRIBUTING.md
- README.md
- apps/papra-client/package.json
- apps/papra-client/src/index.tsx
- apps/papra-client/src/locales/en.yml
- apps/papra-client/src/locales/fr.yml
- apps/papra-client/src/modules/auth/pages/login.page.tsx
- apps/papra-client/src/modules/demo/demo.provider.tsx
- apps/papra-client/src/modules/i18n/i18n.constants.ts
- apps/papra-client/src/modules/i18n/i18n.models.test.ts
- apps/papra-client/src/modules/i18n/i18n.models.ts
- apps/papra-client/src/modules/i18n/i18n.provider.tsx
- apps/papra-client/src/modules/i18n/locales.test.ts
- apps/papra-client/src/modules/i18n/locales.types.ts
- apps/papra-client/src/modules/tags/pages/tags.page.tsx
- apps/papra-client/src/modules/ui/layouts/organization.layout.tsx
- apps/papra-client/src/modules/ui/layouts/sidenav.layout.tsx
- apps/papra-client/src/plugins/yaml-flattened/yaml-flattened.models.ts
- apps/papra-client/src/plugins/yaml-flattened/yaml-flattened.plugin.ts
- apps/papra-client/src/scripts/generate-i18n-types.script.ts
- apps/papra-client/vite.config.ts
- apps/papra-client/vite.env.d.ts
- pnpm-lock.yaml
Base for i18n support, still need to extract strings from tsx
closes #27
> feat(i18n): added internationalization support

- README.md
> docs(README): fix demo link

- apps/papra-client/.env.example
- apps/papra-client/vite.config.ts
> feat(dev): added proxy in client for default backend redirection

- apps/papra-server/migrations/0004_auth-indexs.sql
- apps/papra-server/migrations/meta/0004_snapshot.json
- apps/papra-server/migrations/meta/_journal.json
- apps/papra-server/src/modules/app/auth/auth.tables.ts
Added indexs as recommended by better auth: https://www.better-auth.com/docs/guides/optimizing-for-performance#using-indexes
> feat(auth): add indexes for auth_sessions and auth_verifications tables

- apps/papra-client/src/modules/demo/demo-api-mock.ts
- apps/papra-client/src/modules/documents/documents.composables.tsx
- apps/papra-client/src/modules/documents/pages/documents.page.tsx
- apps/papra-client/src/modules/organizations/organizations.services.ts
- apps/papra-client/src/modules/organizations/organizations.types.ts
- apps/papra-client/src/modules/ui/layouts/sidenav.layout.tsx
- apps/papra-server/src/modules/documents/documents.repository.test.ts
- apps/papra-server/src/modules/documents/documents.repository.ts
- apps/papra-server/src/modules/documents/documents.table.ts
- apps/papra-server/src/modules/organizations/organizations.routes.ts
- apps/papra-server/src/modules/organizations/organizations.usecases.test.ts
> feat(organizations): added organization statistics

- apps/papra-client/src/modules/documents/components/documents-list.component.tsx
- apps/papra-client/src/modules/documents/documents.composables.tsx
- apps/papra-client/src/modules/documents/documents.services.ts
- apps/papra-client/src/modules/documents/pages/documents.page.tsx
- apps/papra-client/src/modules/tags/components/tag.component.tsx
- apps/papra-client/src/modules/tags/pages/tags.page.tsx
- apps/papra-server/src/modules/documents/documents.repository.ts
- apps/papra-server/src/modules/documents/documents.routes.ts
> feat(documents): add document filtering by tags

- apps/papra-client/src/modules/config/config.ts
> refactor(client, config): update PostHog isEnabled flag to use dedicated env

- SECURITY.md
- apps/docs/src/content/navigation.ts
> feat(legals): add security policy

- apps/papra-client/src/modules/documents/documents.composables.tsx
- apps/papra-server/src/modules/documents/documents.models.test.ts
- apps/papra-server/src/modules/documents/documents.models.ts
- apps/papra-server/src/modules/documents/documents.routes.ts
- apps/papra-server/src/modules/documents/storage/document-storage.config.ts
Set `DOCUMENT_STORAGE_MAX_UPLOAD_SIZE=0` to disable max upload limitation
Closes #204
> feat(documents): made file upload limit disableable

- apps/papra-client/src/modules/documents/components/documents-list.component.tsx
- apps/papra-client/src/modules/documents/document.models.test.ts
- apps/papra-client/src/modules/documents/document.models.ts
> refactor(documents): add functions to retrieve document name and extension

- apps/papra-client/src/modules/documents/components/document-preview.component.tsx
> feat(documents): wrap txt document preview

- apps/papra-client/src/modules/documents/pages/document.page.tsx
- apps/papra-server/src/modules/documents/documents.repository.ts
> feat(documents): enhance document page with alert for content extraction details

- apps/papra-server/src/modules/ingestion-folders/ingestion-folders.config.ts
> fix(ingestion-folders): added schema validation coercion in config

- apps/papra-server/src/modules/documents/documents.repository.ts
- apps/papra-server/src/modules/documents/documents.usecases.ts
> fix(documents): hard delete file in storage driver

- .github/workflows/ci-packages-cli.yaml
- packages/cli/bin/papra.mjs
- packages/cli/build.config.ts
- packages/cli/eslint.config.js
- packages/cli/package.json
- packages/cli/src/cli.ts
- packages/cli/src/client.models.ts
- packages/cli/src/commands/commands.models.ts
- packages/cli/src/commands/config/appdata.ts
- packages/cli/src/commands/config/config.command.ts
- packages/cli/src/commands/config/config.schemas.ts
- packages/cli/src/commands/config/config.services.ts
- packages/cli/src/commands/documents/documents.arguments.ts
- packages/cli/src/commands/documents/documents.command.ts
- packages/cli/src/commands/documents/import/import.command.ts
- packages/cli/src/config.ts
- packages/cli/tsconfig.json
- pnpm-lock.yaml
> feat(cli): setup base cli

- .changeset/chatty-pandas-sin.md
- apps/docs/src/content/docs/03-guides/04-setup-custom-oauth2.mdx
- apps/docs/src/content/navigation.ts
- apps/papra-client/src/modules/auth/auth.models.ts
- apps/papra-client/src/modules/auth/auth.services.ts
- apps/papra-client/src/modules/auth/auth.types.ts
- apps/papra-client/src/modules/auth/components/sso-provider-button.component.tsx
- apps/papra-client/src/modules/auth/pages/login.page.tsx
- apps/papra-client/src/modules/auth/pages/register.page.tsx
- apps/papra-client/src/modules/config/config.ts
- apps/papra-server/src/modules/app/auth/auth.config.ts
- apps/papra-server/src/modules/app/auth/auth.services.ts
- apps/papra-server/src/modules/config/config.models.test.ts
- apps/papra-server/src/modules/config/config.models.ts
> feat(auth): added support for custom oauth2 providers

- .changeset/stale-deer-send.md
- apps/papra-server/src/modules/emails/drivers/email-driver.models.ts
- apps/papra-server/src/modules/emails/drivers/email-driver.ts
- apps/papra-server/src/modules/emails/drivers/logger/logger.email-driver.config.ts
- apps/papra-server/src/modules/emails/drivers/logger/logger.email-driver.ts
- apps/papra-server/src/modules/emails/drivers/resend/resend.email-driver.config.ts
- apps/papra-server/src/modules/emails/drivers/resend/resend.email-driver.ts
- apps/papra-server/src/modules/emails/emails.config.ts
- apps/papra-server/src/modules/emails/emails.services.ts
- apps/papra-server/src/modules/emails/emails.types.ts
> refactor(emails): restructure emails service to support multiple drivers

- .changeset/tangy-feet-read.md
- apps/papra-client/src/modules/config/config.ts
- apps/papra-client/src/modules/ui/layouts/sidenav.layout.tsx
> fix(client): corrected version release link

- .changeset/big-walls-tell.md
- apps/papra-client/src/locales/de.yml
- apps/papra-client/src/locales/en.yml
- apps/papra-client/src/locales/fr.yml
- apps/papra-client/src/modules/documents/components/document-preview.component.tsx
- apps/papra-client/src/modules/i18n/locales.types.ts
> feat(preview): improved document preview for text-like files

- .changeset/cruel-rings-juggle.md
- apps/papra-client/src/locales/de.yml
- apps/papra-client/src/locales/en.yml
- apps/papra-client/src/locales/fr.yml
- apps/papra-client/src/locales/pt-BR.yml
- apps/papra-client/src/modules/auth/components/no-auth-provider.tsx
- apps/papra-client/src/modules/auth/pages/login.page.tsx
- apps/papra-client/src/modules/auth/pages/register.page.tsx
- apps/papra-client/src/modules/auth/pages/request-password-reset.page.tsx
- apps/papra-client/src/modules/auth/pages/reset-password.page.tsx
- apps/papra-client/src/modules/config/config.ts
- apps/papra-client/src/modules/i18n/locales.types.ts
- apps/papra-server/src/modules/app/auth/auth.config.ts
- apps/papra-server/src/modules/app/auth/auth.services.ts
- apps/papra-server/src/modules/config/config.models.test.ts
- apps/papra-server/src/modules/config/config.models.ts
> feat(auth): added configuration to disable auth by email

- .changeset/salty-wombats-drop.md
- apps/docs/src/content/docs/02-self-hosting/03-configuration.mdx
> fix(docs): update schema URL in configuration examples to use the correct domain

- .changeset/huge-hands-dream.md
- apps/papra-client/src/locales/ro.yml
- apps/papra-client/src/modules/i18n/i18n.constants.ts
Continues from @iRazvan2745 PR #407 as edits on the PR seems disabled.
Closes #407
> feat(i18n): finalize Romanian translationsetup

- .changeset/cuddly-shoes-watch.md
- .changeset/green-teeth-fall.md
- apps/papra-client/src/locales/de.yml
- apps/papra-client/src/locales/en.yml
- apps/papra-client/src/locales/es.yml
- apps/papra-client/src/locales/fr.yml
- apps/papra-client/src/locales/it.yml
- apps/papra-client/src/locales/pl.yml
- apps/papra-client/src/locales/pt-BR.yml
- apps/papra-client/src/locales/pt.yml
- apps/papra-client/src/locales/ro.yml
- apps/papra-client/src/modules/i18n/locales.types.ts
- apps/papra-client/src/modules/tags/pages/tags.page.tsx
- apps/papra-server/migrations/0007_document-activity-log-on-delete-set-null.sql
- apps/papra-server/migrations/meta/0007_snapshot.json
- apps/papra-server/migrations/meta/_journal.json
- apps/papra-server/src/modules/documents/document-activity/document-activity.table.ts
> fix(tags): fixed the impossibility to delete a tag that have been affected to a document

- .changeset/three-ideas-fix.md
- apps/docs/src/content/docs/02-self-hosting/01-using-docker.mdx
- apps/docs/src/content/docs/04-resources/01-troubleshooting.mdx
- apps/papra-client/src/locales/de.yml
- apps/papra-client/src/locales/en.yml
- apps/papra-client/src/locales/es.yml
- apps/papra-client/src/locales/fr.yml
- apps/papra-client/src/locales/it.yml
- apps/papra-client/src/locales/pl.yml
- apps/papra-client/src/locales/pt-BR.yml
- apps/papra-client/src/locales/pt.yml
- apps/papra-client/src/locales/ro.yml
- apps/papra-client/src/modules/auth/auth.services.ts
- apps/papra-client/src/modules/auth/components/sso-provider-button.component.tsx
- apps/papra-client/src/modules/auth/pages/login.page.tsx
- apps/papra-client/src/modules/auth/pages/register.page.tsx
- apps/papra-client/src/modules/i18n/i18n.models.test.ts
- apps/papra-client/src/modules/i18n/i18n.models.ts
- apps/papra-client/src/modules/i18n/locales.types.ts
- apps/papra-client/src/modules/shared/http/composables/i18n-api-errors.ts
- apps/papra-server/src/modules/app/auth/auth.services.ts
- pnpm-lock.yaml
- pnpm-workspace.yaml
> feat(auth): improved feedback for invalid origin url

- .changeset/rich-parents-flash.md
- .changeset/sweet-cougars-bathe.md
- .changeset/young-laws-wish.md
- apps/papra-client/src/locales/de.yml
- apps/papra-client/src/locales/en.yml
- apps/papra-client/src/locales/es.yml
- apps/papra-client/src/locales/fr.yml
- apps/papra-client/src/locales/it.yml
- apps/papra-client/src/locales/pl.yml
- apps/papra-client/src/locales/pt-BR.yml
- apps/papra-client/src/locales/pt.yml
- apps/papra-client/src/locales/ro.yml
- apps/papra-client/src/modules/command-palette/command-palette.provider.tsx
- apps/papra-client/src/modules/demo/demo-api-mock.models.ts
- apps/papra-client/src/modules/demo/demo-api-mock.ts
- apps/papra-client/src/modules/documents/components/document-content-edition-panel.component.tsx
- apps/papra-client/src/modules/documents/pages/document.page.tsx
- apps/papra-client/src/modules/i18n/locales.types.ts
- apps/papra-server/src/modules/documents/documents.routes.ts
Closes #466 
- Added content edition support in demo mode
- Use the same textarea for display and edition 
- Cleanup the code and state management logic
> refactor(documents): improved UX of the document content update

- .changeset/brave-parrots-fold.md
- apps/papra-client/src/modules/documents/components/document-preview.component.tsx
- apps/papra-client/src/modules/documents/pages/document.page.tsx
- apps/papra-client/src/modules/organizations/pages/organization.page.tsx
> refactor(documents): lazy load PdfViewer component for smaller main chunk

- .changeset/lazy-tables-cover.md
- apps/papra-server/src/modules/tags/tags.repository.test.ts
- apps/papra-server/src/modules/tags/tags.repository.ts
> fix(tags): retreive tags affected even when only affected to deleted documents

- .changeset/forty-ducks-switch.md
- apps/papra-client/src/locales/de.dictionary.ts
- apps/papra-client/src/locales/en.dictionary.ts
- apps/papra-client/src/locales/es.dictionary.ts
- apps/papra-client/src/locales/fr.dictionary.ts
- apps/papra-client/src/locales/it.dictionary.ts
- apps/papra-client/src/locales/pl.dictionary.ts
- apps/papra-client/src/locales/pt-BR.dictionary.ts
- apps/papra-client/src/locales/pt.dictionary.ts
- apps/papra-client/src/locales/ro.dictionary.ts
- apps/papra-client/src/modules/intake-emails/pages/intake-emails.page.tsx
- apps/papra-client/src/modules/shared/http/composables/i18n-api-errors.ts
- apps/papra-server/package.json
- apps/papra-server/src/modules/intake-emails/intake-emails.errors.ts
- apps/papra-server/src/modules/intake-emails/intake-emails.repository.ts
- apps/papra-server/src/modules/intake-emails/intake-emails.routes.ts
- apps/papra-server/src/modules/intake-emails/intake-emails.usecases.ts
- apps/papra-server/src/modules/intake-emails/username-drivers/intake-email-username.config.ts
- apps/papra-server/src/modules/intake-emails/username-drivers/intake-email-username.drivers.ts
- apps/papra-server/src/modules/intake-emails/username-drivers/intake-email-username.models.ts
- apps/papra-server/src/modules/intake-emails/username-drivers/intake-email-username.services.ts
- apps/papra-server/src/modules/intake-emails/username-drivers/pattern/pattern.intake-email-username-driver.config.ts
- apps/papra-server/src/modules/intake-emails/username-drivers/pattern/pattern.intake-email-username-driver.constants.ts
- apps/papra-server/src/modules/intake-emails/username-drivers/pattern/pattern.intake-email-username-driver.ts
- apps/papra-server/src/modules/intake-emails/username-drivers/random/random.intake-email-username-driver.ts
- pnpm-lock.yaml
> feat(intake-emails): add intake email username pattern config

- .changeset/calm-heads-clap.md
- apps/papra-server/package.json
- apps/papra-server/src/modules/tasks/drivers/libsql/libsql.tasks-driver.ts
- apps/papra-server/src/modules/tasks/tasks.config.ts
- pnpm-lock.yaml
Related to https://github.com/papra-hq/cadence-mq/pull/29
> feat(tasks): add option to disable PRAGMA statements in migrations

- .changeset/big-beans-win.md
- .github/workflows/release-docker.yaml
- docker/Dockerfile
- docker/Dockerfile.rootless
- package.json
> feat(docker): drop support for armv7
